### ISSUE TITLE
Move entity members under a 'members' property under each entity

### ISSUE THREAD

**Issue by angrifel** [angrifel/gen-mdl#3]
Currently entity members are listed just below the entity level.

They belong to a separate propery.

Current design

```
...
entities:
  entity_1:
    member_1_a: ...
    member_1_b: ...
    ...
    member_1_z: ...

  entity_2:
    member_2_a: ...
    member_2_b: ...
    ...
    member_2_z: ...

''''
```

expected design

```
...
entities:
  entity_1:
    members:
      member_1_a: ...
      member_1_b: ...
      ...
      member_1_z: ...

  entity_2:
    members:
      member_2_a: ...
      member_2_b: ...
      ...
      member_2_z: ...

...
```
