### ISSUE TITLE
Add Validations to model

### ISSUE THREAD

**Issue by angrifel** [angrifel/gen-mdl#30]
We should allow validations to occur on the model at different levels.
- [ ] at the field level
```yaml
entities:
  entity_1:
    ...
    members:
      field_1: ...
      field_2:
        type: ...
        validations: 
          validation_name_1 : [validation rule here]
          validation_name_2 : [validation rule here]
          #other validations here
      #other fields here
  entity_2: ...
  #other entities here
```

- [ ] at the entity level
```yaml
entities:
  entity_1:  ...
    members: ...
    validations: 
      validation_name_1 : [validation rule here]
      validation_name_2 : [validation rule here]
      #other validations here
  entity_2: ...
  #other entities here
```

- [ ] at the model level.

```yaml
enums: ...

entities: ...

validations: 
  validation_name_1 : [validation rule here]
  validation_name_2 : [validation rule here]
  #other validations here

```
